---
development:
  cloud_name: flampic
  api_key: '333169189687311'
  api_secret: kqXVte1LTbMllETzF9MySTOHUds
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: flampic
  api_key: '333169189687311'
  api_secret: kqXVte1LTbMllETzF9MySTOHUds
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: flampic
  api_key: '333169189687311'
  api_secret: kqXVte1LTbMllETzF9MySTOHUds
  enhance_image_tag: true
  static_image_support: false
